### ISSUE TITLE
rule OZH RAT needs to be "rule OZH_RAT"

### ISSUE THREAD

**Issue by morrowd** [WilliamThomas-sec/IOCs#1]
`yara -r OZH_RAT.yar ~/Malware/
OZH_RAT.yar(8): error: syntax error, unexpected identifier, expecting '{'`

YARA doesn't allow spaces or dashes in rule names. Underscores are fine.

Regards,

Dax

**Comment by BushidoUK** [comment]
Sorted, thank you!
